export const SET_GITHUB_TOKEN = 'SET_GITHUB_TOKEN'
export const CLEAR_GITHUB_TOKEN = 'CLEAR_GITHUB_TOKEN'
export const RESTORE_GITHUB_TOKEN = 'RESTORE_GITHUB_TOKEN'

export const STARS_PULL_STARTED = 'STARS_PULL_STARTED'
export const STARS_PULL_FINISHED = 'STARS_PULL_FINISHED'
export const STARS_PULL_ERROR = 'STARS_PULL_ERROR'
export const APPEND_STARS = 'APPEND_STARS'
